#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
dunst &
xcompmgr &
dwmblocks &
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
exec dwm
